/*
 * Copyright 2016-2022 the original author or authors.
 *
 * All rights reserved. This program and the accompanying materials are
 * made available under the terms of the Eclipse Public License v2.0 which
 * accompanies this distribution and is available at
 *
 * http://www.eclipse.org/legal/epl-v20.html
 */

package org.junitpioneer.jupiter;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;
import static org.junit.jupiter.api.Assertions.fail;
import static org.junitpioneer.testkit.assertion.PioneerAssert.assertThat;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junitpioneer.testkit.ExecutionResults;
import org.junitpioneer.testkit.PioneerTestKit;
import org.opentest4j.TestAbortedException;

@DisplayName("NotWorking extension")
public class NotWorkingExtensionTests {

	@Test
	void abortsOnTestFailure() {
		ExecutionResults results = PioneerTestKit.executeTestMethod(NotWorkingTestCases.class, "failure");
		assertThat(results)
				.hasSingleStartedTest()
				.whichAborted()
				.withExceptionInstanceOf(TestAbortedException.class)
				.hasMessage("Test marked as 'not working' failed as expected");
	}

	@Test
	void abortsOnTestFailureWithMetaAnnotation() {
		ExecutionResults results = PioneerTestKit.executeTestMethod(NotWorkingTestCases.class, "metaAnnotationFailure");
		assertThat(results)
				.hasSingleStartedTest()
				.whichAborted()
				.withExceptionInstanceOf(TestAbortedException.class)
				.hasMessage("Test marked as 'not working' failed as expected");
	}

	@Test
	void abortsOnTestFailureWithMessage() {
		ExecutionResults results = PioneerTestKit.executeTestMethod(NotWorkingTestCases.class, "failureWithMessage");
		assertThat(results)
				.hasSingleStartedTest()
				.whichAborted()
				.withExceptionInstanceOf(TestAbortedException.class)
				.hasMessage("Custom message");
	}

	@Test
	void abortsOnError() {
		ExecutionResults results = PioneerTestKit.executeTestMethod(NotWorkingTestCases.class, "error");
		assertThat(results)
				.hasSingleStartedTest()
				.whichAborted()
				.withExceptionInstanceOf(TestAbortedException.class)
				.hasMessage("Test marked as 'not working' failed as expected");
	}

	@Test
	void preservesTestAbort() {
		ExecutionResults results = PioneerTestKit.executeTestMethod(NotWorkingTestCases.class, "aborted");
		assertThat(results)
				.hasSingleStartedTest()
				.whichAborted()
				.withExceptionInstanceOf(TestAbortedException.class)
				// Ignore prefix generated by JUnit
				.hasMessageEndingWith("custom assumption message");
	}

	@Test
	void failsOnWorkingTest() {
		ExecutionResults results = PioneerTestKit.executeTestMethod(NotWorkingTestCases.class, "working");
		assertThat(results)
				.hasSingleStartedTest()
				.whichFailed()
				.withExceptionInstanceOf(AssertionError.class)
				.hasMessage("Test marked as 'not working' succeeded; remove @NotWorking from it");
	}

	@Test
	void doesNotAbortOnBeforeEachTestFailure() {
		ExecutionResults results = PioneerTestKit.executeTestMethod(NotWorkingFailureBeforeEachTestCases.class, "test");
		assertThat(results)
				.hasSingleFailedTest()
				.withExceptionInstanceOf(AssertionError.class)
				.hasMessage("before each");
	}

	@Test
	void abortsOnAfterEachTestFailure() {
		ExecutionResults results = PioneerTestKit.executeTestMethod(NotWorkingFailureAfterEachTestCases.class, "test");
		assertThat(results)
				.hasSingleStartedTest()
				.whichAborted()
				.withExceptionInstanceOf(TestAbortedException.class)
				.hasMessage("Test marked as 'not working' failed as expected");
	}

	@Test
	void abortsOnAfterEachTestFailureAfterTestAbort() {
		ExecutionResults results = PioneerTestKit
				.executeTestMethod(NotWorkingAbortThenFailureAfterEachTestCases.class, "test");
		assertThat(results)
				.hasSingleStartedTest()
				.whichAborted()
				.withExceptionInstanceOf(TestAbortedException.class)
				// Ignore prefix generated by JUnit
				.hasMessageEndingWith("custom assumption message")
				// Exception thrown by extension is added as suppressed by JUnit's ThrowableCollector
				.hasSuppressedException(new TestAbortedException("Test marked as 'not working' failed as expected"));
	}

	@Test
	void preservesAfterEachAbortAfterTestFailure() {
		ExecutionResults results = PioneerTestKit
				.executeTestMethod(NotWorkingFailureThenAbortAfterEachTestCases.class, "test");
		assertThat(results)
				.hasSingleStartedTest()
				.whichAborted()
				.withExceptionInstanceOf(TestAbortedException.class)
				// Ignore prefix generated by JUnit
				.hasMessageEndingWith("custom assumption message");
	}

	@Test
	void doesNotAbortOnBeforeAllTestFailure() {
		ExecutionResults results = PioneerTestKit.executeTestMethod(NotWorkingFailureBeforeAllTestCases.class, "test");
		assertThat(results).hasNumberOfStartedTests(0);
		assertThat(results)
				.hasSingleFailedContainer()
				.withExceptionInstanceOf(AssertionError.class)
				.hasMessage("before all");
	}

	@Test
	void doesNotAbortOnAfterAllTestFailure() {
		ExecutionResults results = PioneerTestKit.executeTestMethod(NotWorkingFailureAfterAllTestCases.class, "test");
		assertThat(results)
				.hasSingleStartedTest()
				.whichFailed()
				.withExceptionInstanceOf(AssertionError.class)
				.hasMessage("Test marked as 'not working' succeeded; remove @NotWorking from it");
	}

	static class NotWorkingTestCases {

		@NotWorking
		@Retention(RUNTIME)
		@Target(METHOD)
		@interface NotWorkingMetaAnnotation {
		}

		@NotWorking
		@Test
		void failure() {
			fail("failed");
		}

		@NotWorkingMetaAnnotation
		@Test
		void metaAnnotationFailure() {
			fail("failed");
		}

		@NotWorking("Custom message")
		@Test
		void failureWithMessage() {
			fail("failed");
		}

		@NotWorking
		@Test
		void error() {
			throw new RuntimeException("test");
		}

		@NotWorking
		@Test
		void aborted() {
			// Assumption should have higher precedence than @NotWorking
			Assumptions.assumeTrue(false, "custom assumption message");
		}

		@NotWorking
		@Test
		void working() {
			// Does not cause failure or error
		}

	}

	/**
	 * {@link BeforeEach} should not be considered by {@link NotWorking} because it
	 * is not specific to the annotated test method.
	 */
	static class NotWorkingFailureBeforeEachTestCases {

		@BeforeEach
		void beforeEach() {
			fail("before each");
		}

		@NotWorking
		@Test
		void test() {
		}

	}

	/**
	 * {@link AfterEach} should be considered by {@link NotWorking} because it
	 * might fail due to changes made to the test instance by the test method.
	 */
	static class NotWorkingFailureAfterEachTestCases {

		@AfterEach
		void afterEach() {
			fail("after each");
		}

		@NotWorking
		@Test
		void test() {
		}

	}

	/**
	 * Abort in test method followed by failure in {@link AfterEach} method should
	 * be treated as expected failure.
	 */
	static class NotWorkingAbortThenFailureAfterEachTestCases {

		@AfterEach
		void afterEach() {
			fail("after each");
		}

		@NotWorking
		@Test
		void test() {
			Assumptions.assumeTrue(false, "custom assumption message");
		}

	}

	/**
	 * Failure in test method followed by abort in {@link AfterEach} method should
	 * preserve that abort.
	 */
	static class NotWorkingFailureThenAbortAfterEachTestCases {

		@AfterEach
		void afterEach() {
			// Assumption should have higher precedence than @NotWorking
			Assumptions.assumeTrue(false, "custom assumption message");
		}

		@NotWorking
		@Test
		void test() {
			fail("failed");
		}

	}

	/**
	 * {@link BeforeAll} should not be considered by {@link NotWorking}.
	 */
	static class NotWorkingFailureBeforeAllTestCases {

		@BeforeAll
		static void beforeAll() {
			fail("before all");
		}

		@NotWorking
		@Test
		void test() {
		}

	}

	/**
	 * {@link AfterAll} should not be considered by {@link NotWorking}.
	 */
	static class NotWorkingFailureAfterAllTestCases {

		@AfterAll
		static void afterAll() {
			fail("after all");
		}

		@NotWorking
		@Test
		void test() {
		}

	}

}
